In [ ]:
dataset

In [7]:
!pip install tqdm fastparquet

Requirement already satisfied: tqdm in ./.venv/lib/python3.14/site-packages (4.70.0)
Collecting fastparquet
  Downloading fastparquet-2026.5.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (4.8 kB)
Requirement already satisfied: pandas>=1.5.0 in ./.venv/lib/python3.14/site-packages (from fastparquet) (3.0.5)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (from fastparquet) (2.5.2)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.12.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (1.2 kB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in ./.venv/lib/python3.14/site-packages (from fastparquet) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.5.0-cp314-cp314-macosx_11_0_arm64.whl (722 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 722.7/722.7 kB 19.5 MB/s  0:00:00
Downloading cramjam-2.12.1-cp314-cp314-macosx_11_0_arm64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 58.6 MB/s  0:00:00
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
Installing collected packages: fsspec, cramjam, fastparquet
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [fastparquet]
Successfully installed cramjam-2.12.1 fastparquet-2026.5.0 fsspec-2026.7.0

In [6]:
import requests
import yaml
import getpass
# import zstandard as zstd
import pandas as pd
import json
import io

from typing import Dict, List, Any
from tqdm import tqdm

In [31]:
df_queries = pd.read_parquet('esci-data/shopping_queries_dataset/shopping_queries_dataset_examples.parquet')
df_queries = df_queries[df_queries["product_locale"] == "us"]

In [32]:
df_queries.head(5)

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train

In [37]:
unique_queries = df_queries["query"].drop_duplicates()

In [38]:
len(unique_queries)

97345

In [39]:
unique_queries.head(5)

0                                revent 80 cfm
16                !awnmower tires without rims
32                !qscreen fence without holes
149    # 10 self-seal envelopes without window
189                  # 2 pencils not sharpened
Name: query, dtype: object

In [40]:
random_queries = unique_queries.sample(n=1000, random_state=42)
len(random_queries)

1000

In [27]:
df_products = pd.read_parquet('esci-data/shopping_queries_dataset/shopping_queries_dataset_products.parquet')
df_products = df_products[df_products["product_locale"] == "us"]
df_products.head(5)

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
167168,B003O0MNGC,Delta BreezSignature VFB25ACH 80 CFM Exhaust B...,None,Virtually silent at less than 0.3 sones\nPreci...,DELTA ELECTRONICS (AMERICAS) LTD.,White,us
167169,B00MARNO5Y,Aero Pure AP80RVLW Super Quiet 80 CFM Recessed...,None,Super quiet 80CFM energy efficient fan virtual...,Aero Pure,White,us
167170,B011RX6PNO,Aero Pure AP120H-SL W Slim Fit 120 CFM Bathroo...,None,"Slim Fit Housing Fits Into 2"" X 6"" Ceiling Joi...",Aero Pure,White Finish,us
167171,B01MZIK0PI,Delta Electronics (Americas) Ltd. RAD80 Delta ...,None,Quiet operation at 1.5 Sones\nPrecision engine...,DELTA ELECTRONICS (AMERICAS) LTD.,With Heater,us
167172,B01N5Y6002,Delta Electronics (Americas) Ltd. GBR80HLED De...,None,Ultra energy-efficient LED module (11-watt equ...,DELTA ELECTRONICS (AMERICAS) LTD.,"With LED Light, Dual Speed & Humidity Sensor",us

In [42]:
df_random_queries = df_queries[
    df_queries["query"].isin(random_queries)
]

In [43]:
df = pd.merge(
    df_random_queries,
    df_products,
    how='left',
    left_on=['product_locale','product_id'],
    right_on=['product_locale', 'product_id']
)
df.head(5)

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split,product_title,product_description,product_bullet_point,product_brand,product_color
0,3042,$5 items,100,B079HXXP4T,us,I,1,1,test,"Soft Scrub In-Tank Toilet Cleaner Duo-Cubes, A...",None,"Helps fight toilet ring, hard water, and limes...",Soft Scrub,Alpine Fresh
1,3043,$5 items,100,B07DZYGDS3,us,E,1,1,test,"Gillette Fusion5 Razors for Men, 1 Gillette Ra...",None,REFILLS FIT ALL GILLETTE 5-BLADE RAZOR HANDLES...,Gillette,None
2,3044,$5 items,100,B07HY9DC4N,us,E,1,1,test,"Summer's Eve Cleansing Cloths, Blissful Escape...",None,Summer's Eve Feminine Cleansing Wipes are safe...,Summer's Eve,None
3,3045,$5 items,100,B07M77RB97,us,E,1,1,test,BIC Flex 5 Hybrid Men's 5-Blade Disposable Raz...,None,"5 long lasting, flexible blades individually a...",BIC,Black
4,3046,$5 items,100,B07NTWYGJX,us,I,1,1,test,"6PCS Dual Heads Blackhead Remover, Pimple Come...",<b>About Our Factory:</b><br /> ✿✿Our factory ...,"♥ 【Dual Heads REMOVER】: 6PCS dual heads tools,...",USCOLOR,None

In [50]:
len(df)

18727

In [ ]:
index

In [45]:
SEARCH_INDEX = 'http://localhost:9200/myindex'

In [46]:
idx = requests.put(
    SEARCH_INDEX,
    json={
        "mappings": {
            "properties": {
                "name": {
                    "type": "text"
                },
                "description": {
                    "type": "text"
                }
            }
        }
    }
)
idx.json()

{'acknowledged': True, 'shards_acknowledged': True, 'index': 'myindex'}

In [47]:
def index_record(id, name, description):
    if id and name and description:
        try:
            return requests.post(
                f"{SEARCH_INDEX}/_doc/{id}",
                json={
                    'name': name,
                    'description': description    
                }
            )
        except:
            pass

In [48]:
for index, row in tqdm(df.iterrows(), total=len(df)):
    _ = index_record(row['example_id'], row['product_title'], row['product_description'])

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 18727/18727 [00:23<00:00, 808.38it/s]

In [49]:
response = requests.post(
    f"{SEARCH_INDEX}/_search",
    json={
        "size": 0,
        "track_total_hits": True
    }
)
response.json()

{'took': 256,
 'timed_out': False,
 'terminated_early': False,
 '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
 'hits': {'total': {'value': 9295, 'relation': 'eq'},
  'max_score': None,
  'hits': []}}

In [52]:
def search_query(query='#$query##'):
    return {
      "query": {
        "multi_match": {
          "query": query,
          "fields": [f"name", "description"]
        }
      }
    }
    
def search(query):
    response = requests.post(
        f"{SEARCH_INDEX}/_search",
        json=search_query(query)
    )
    return response.json()

In [53]:
search('dinosaur')

{'took': 49,
 'timed_out': False,
 '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
 'hits': {'total': {'value': 31, 'relation': 'eq'},
  'max_score': 13.017879,
  'hits': [{'_index': 'myindex',
    '_id': '1975317',
    '_score': 13.017879,
    '_source': {'name': 'Baby Dinosaur Balloon Set for Birthday Decor - 38 Inch, Pack of 4, 4D Dinosaur Foil Balloon | Kids Dinosaur Party Decorations | Dinosaur Balloons for Birthday Party | Dinosaur Birthday Party Supplies',
     'description': '<p><b>Are you a dinasaur fanatic?</b></p><p>Looking for a dinosaur theme party decorations for your kid</p> <p>We have got you covered with these beautiful and gigantic <b>Baby Dinosaur Foil Balloons </b> in two different style of dinosaur party balloons </p> <p>This dinosaur balloon kit is simply beautiful, gorgeous color to your dinosaur balloon birthday party as a backdrop for photos Booth.</p> <p>Configure it any way you wish; there are 1000s of ways to use your kit to build your beautiful dinosaur birthday balloons background for your dinosaur party decorations. that includes triceratops dinosaur mylar balloon, Ceratosaurus dinosaur ballons, Long neck dinosaur balloons,Green Tyrannosaurus dinosaur balloons t rex</p> <p><b>What you will get :</b></p> <p>1.) Dark Green Baby Dinosaur Foil Balloons - 27 X 24 Inch, helium supported </p> <p>2.) Baby Dinosaur Foil Balloons - 35 X 27 Inch, Helium Supported </p> <p>3.) Green Dinosaur Foil Balloons - 38 X 27 Inch, Helium Supported </p> <p>4.) Long Neck Thunder Dragon Yellow Dinosaur Balloon - 33 X 30 Inch, Helium Supported </p> <p>5.) White Ribbon Roll: 32 Feet</p> <p>6.) White Straw To Inflate</p> <p>Glaze up and feed your excitement while decorating your helium dinosaur balloons birthday with dino balloons.</p> <p><b>Suggested Uses :</b></p> <p>- Standing dinosaur balloons girl for Dinosaur Theme Party decorations</p> <p>- Dinosaur Birthday Party Supplies with T-Rex Foil Balloons<br><br />- Jungle Theme blue dinosaur decorations for birthday party<br /><br />- Dinosaur balloon garland kit as a backdrop for photo props and centerpiece<br /><br />- Dinosaur Balloons For Birthday Party<br /><br />- Safari themed dinosaurs balloons for childrens party<br /><br />- Dinosaur Balloons Big for 1st birthday decoration</p> <p>- Rawr Dinosaur Balloon Baby Shower, Dinosaur Three Rex dinosaur balloon girl party</p> <p><b>Click Add to Cart</b> and make your party memorable with our Beautiful Baby Dinosaur Balloons</p>'}},
   {'_index': 'myindex',
    '_id': '1120381',
    '_score': 11.201096,
    '_source': {'name': 'Jurassic World Legacy Collection Exclusive Brachiosaurus Action Figure',
     'description': 'The Jurassic World Legacy Collection roars into action celebrating classic moments, themes and characters from the blockbuster film franchise! Inspired by the Brachiosaurus from the original Jurassic Park film, this approximately 28-inches high and 34-inches long dinosaur figure features movie-inspired sculpting, authentic color and realistic texture. The Brachiosaurus figure also has multiple points of neck, leg, tail, and jaw articulation for multiple moves and posing possibilities! Play out all the exciting action and adventure of Jurassic Park with this larger-sizer Brachiosaurus dinosaur action figure. For more dinosaur fun, download the Jurassic World Facts app (Android and iOS) to scan and watch your dinosaur come to life, learn attack facts, compare stats and more! Colors and decorations may vary. For ages 4 and up.'}},
   {'_index': 'myindex',
    '_id': '96438',
    '_score': 10.666865,
    '_source': {'name': '3D Lenticular Dinosaur Playing Card Deck - by Artgame',
     'description': 'Stunning collection of 54 unique Dinosaur cards. Each card is an original 3D art piece by Royce McClure that includes the common name of the featured dinosaur. Cards are made of durable plastic for excellent wear and play.These make an excellent gift for both dino fans and card players alike. Check out our Amazon store - More designs available !'}},
   {'_index': 'myindex',
    '_id': '250719',
    '_score': 9.61051,
    '_source': {'name': '1st Birthday Girl T-Shirt Dinosaur Party B-Day Themed Tee Gift for Baby Dino First Birthday T Shirt Cotton Short Sleeve T-Rex Printed Embroidery Graphic Top Clothes (White, 1T)',
     'description': '☛Simple Crew neckline tee design is perfect paired with a variety of pants and coats. ☛DO NOT washing with hot water. Machine wash or hand wash available, hanging to dry. ☛A excellent birthday girls t-shirt. Putting on cute dinosaur shirt to your birthday party must be a cool thing! ☛Due to body difference, please kindly check our size chart. ☛1T- 80---Bust Width 11.4", Tee length 13.8", Sleeve length 4.5". Recommended Height: 29-31", Weight: 21-24lb 2T-90---Bust Width 12.2", Tee length 14.9", Sleeve length 4.7". Recommended Height: 33-35", Weight: 26-29lb <B>Package included ☛1x girl dinosaur birthday Tee.'}},
   {'_index': 'myindex',
    '_id': '1120384',
    '_score': 9.454461,
    '_source': {'name': "Jurassic World Thrash'N Throw Tyrannosaurus Rex (Move Taill for Thrashing & Throwing, Roars, Bites, Stomps) Ages 4+ New",
     'description': "Get ready for thrilling action and adventure with Jurassic World! In the style of the fan-favorite character from the original Jurassic Park films, Thrash 'n Throw Tyrannosaurus Rex is back and better than ever with awesome action features! In addition to authentic sculpt and decoration, Thrash 'n Throw Tyrannosaurus Rex has sound effect features like chomping and stomping, an impressive roar and a HUGE bite Tail activation lets Thrash 'n Throw Tyrannosaurus Rex open her mouth to pick up other character and dinosaur action figures, and then thrash and throw them across the room! Recreate epic dinosaur action scenes from the movie, but watch out—this Tyrannosaurus Rex is ready for a fight!"}},
   {'_index': 'myindex',
    '_id': '160387',
    '_score': 9.172341,
    '_source': {'name': 'Silver Lilly Dinosaur Costume - Trex Cosplay - Reptile One Piece Pajama (Green Dinosaur, M)',
     'description': "Dress to impress in these Plush Dinosaur Animal One-Piece Pajamas from Silver Lilly. Crafted from ultra-soft 100% polyester, this cozy bodysuit will be a hit at any party, cosplay event, or pajama sleepover. Intricate detailing on the head, body, and tail bring this character to life, so you'll be the life of the party. Two front pockets are included and are convenient for storing your eye mask, earplugs, phone or wallet. The loose fit is comfortable and won't restrict your movements, giving you the freedom to sleep, dance or perform as you please. For best results hand wash, lay flat to dry, and iron on low heat if needed. Multiple sizes available, see size chart for details."}},
   {'_index': 'myindex',
    '_id': '672909',
    '_score': 8.917696,
    '_source': {'name': 'Dinosaur Doodles Gift Wrapping Paper Roll - 24" x 15\'',
     'description': 'Take your dino-themed birthday to the next level with this awesome Jurassic wrapping paper! Features colorful dinosaur crayon doodles on a white background. Roll measures 24"W x 15\'L = 30 sq ft of paper. Measured, hand-cut and rolled to order - so no creases!'}},
   {'_index': 'myindex',
    '_id': '96435',
    '_score': 8.652658,
    '_source': {'name': 'Kikkerland 3-D Dinosaurs - Lenticular Playing Cards',
     'description': '<b>3-D Dinosaurs - Lenticular Playing Cards </b> Collectable playing card deck featuring 3D style lenticular dinosaurs Each card depicts a different dinosaur illustration that changes as you move the card Pterodactyl to T-Rex - the perfect pack for dino fans of all ages Standard deck of cards - perfect for patience, poker, bridge or whist'}},
   {'_index': 'myindex',
    '_id': '672913',
    '_score': 8.588842,
    '_source': {'name': 'Dinosaur Bash Gift Wrapping Paper Roll - 24" x 15\'',
     'description': 'Bring the dinos to your next party with this fun gift wrapping paper! Features colorful dinosaurs having a party with cake, party hats and palm trees. Measured, hand-cut and rolled to order - so no creases! Roll measures 24"W x 15\'L = 30 sq ft of paper. A fun addition to any dinosaur-themed party or celebration!'}},
   {'_index': 'myindex',
    '_id': '672917',
    '_score': 7.7184978,
    '_source': {'name': 'Bamboo Muslin Swaddle Blankets for Boys - 2 Pack Dinosaur & Tropical Bamboo Baby Boy Blanket Toddler Blanket - Large Summer Baby Muslin Blanket Swaddle Wrap(Dinosaur & Tropical)',
     'description': "The Little Jump brand was created out of a mother's love and desire to keep her baby safe, protected and comfortable. We take pride in creating beautifully designed products with gorgeous colours and patterns that both parents and children will love. From our family to yours, we wish you health and happiness throughout your parenting journey, and we look forward to being a part of it."}}]}}

## judge

In [ ]:
train student

In [ ]:
compare

In [ ]:
human labels - better teacher - dspy??

In [ ]:
https://github.com/amazon-science/esci-data/blob/main/shopping_queries_dataset/shopping_queries_dataset_products.parquet